version: '3.8'
services:
  db:
    image: mysql:8
    container_name: buyway_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buyway_database
      MYSQL_USER: buyway_user
      MYSQL_PASSWORD: buyway_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./Aliexpress-Backend
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=buyway_database;User=buyway_user;Password=buyway_password;
    depends_on:
      - db

  frontend:
    build: ./Aliexpress-Frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
